services:
 - docker

branches:
  only:
  - master

before_script:
 - docker build -f Dockerfile -t pumpkins .

script:
  - docker run --rm -it -v $PWD:/staging -w /staging pumpkins python3 -B -m pytest -p no:cacheprovider
